### ISSUE TITLE
When exiting via flag pole i get this error which never happened until i switched saves

### ISSUE THREAD

**Issue by Mememan11** [SpencerEverly/smasplusplus#1]
![16628660193896067327836578027684](https://user-images.githubusercontent.com/17150289/189510855-0abb359b-1da9-4380-a5c3-7b8a8d309f37.jpg)

**Comment by SpencerEverly** [comment]
That shouldn't happen outside of the LunaLua SEE Mod (A thing I'm working on separate from the SMBX2 build most people have).

Are you on the version downloaded from the Codehaus website?

**Comment by Mememan11** [comment]
Nope it was the LunaLua SEE version. But it works now when it updated.
