### ISSUE TITLE
Looks like I am back again, I found a level glitch I think. I don't know what's going on but it keeps happening. The bug leaves a empty area at the beginning of any level or section.

### ISSUE THREAD

**Issue by ultimategamerdad** [SpencerEverly/smasplusplus#2]
![image](https://user-images.githubusercontent.com/17150289/190269006-f929ff9d-c4ce-4402-94b5-e42db22cc57b.png)

**Comment by SpencerEverly** [comment]
Where is that from? I’m gonna have to check up on the level itself

**Comment by ultimategamerdad** [comment]
Seems to be in any Super Mario Bros. or Lost Level stages.

**Comment by SpencerEverly** [comment]
Looks like it might be a bug with the reimplemented no turn back system on other miscellaneous resolutions. I'm gonna take a look at it soon

**Comment by SpencerEverly** [comment]
Should now be fixed! Check to see if it's fully fixed, and if it is, you can close this issue if you want.
