### ISSUE TITLE
After beating bowser the second time in 8-4 of Super Mario Bros. when the timer gets to 100 this error keeps popping up no matter how many times it is closed unless you close the game.

### ISSUE THREAD

**Issue by ultimategamerdad** [SpencerEverly/smasplusplus#3]
![image](https://user-images.githubusercontent.com/17150289/190408695-6453c63f-cd11-4d27-9439-d089ff293cd7.png)

**Comment by ultimategamerdad** [comment]
I suspect it is something to do with the music and a sped up track.

**Comment by SpencerEverly** [comment]
You have to be on the latest SEE Mod version if you’re not updated to that. I didn’t clarify publicly that it gets updated at times, my bad. You can download the latest SEE Mod here: https://github.com/SpencerEverly/smbx2-seemod
